/**
 * generate.mjs
 *
 * Generates repository health files based on user answers and detected stack.
 * Can operate in init mode (create everything) or update mode (fill gaps only).
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { detectStack, gitignoreTemplates, dependabotEcosystems, STACK_META } from './detect-stack.mjs';

/**
 * Fetch .gitignore content from the gitignore.io API.
 * Falls back to a bundled minimal template on failure.
 *
 * @param {string[]} templates - Template names (e.g., ['node', 'macos']).
 * @returns {Promise<string>}
 */
export async function fetchGitignore(templates) {
  const url = `https://www.toptal.com/developers/gitignore/api/${templates.join(',')}`;
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(10_000) });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return await res.text();
  } catch {
    // Fallback: return a minimal .gitignore
    return [
      '# Generated by repo-ready (offline fallback)',
      'node_modules/',
      'dist/',
      'build/',
      '.env',
      '.env.local',
      '.DS_Store',
      'Thumbs.db',
      '*.log',
      '',
    ].join('\n');
  }
}

/**
 * Fetch a license body from the GitHub Licenses API.
 *
 * @param {string} spdxId - License SPDX identifier (e.g., 'mit').
 * @param {{ owner: string, year: string|number }} vars - Template variables.
 * @returns {Promise<string>}
 */
export async function fetchLicense(spdxId, vars = {}) {
  const url = `https://api.github.com/licenses/${spdxId}`;
  try {
    const res = await fetch(url, {
      headers: { Accept: 'application/vnd.github+json' },
      signal: AbortSignal.timeout(10_000),
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    let body = data.body || '';
    body = body.replace(/\[year\]/g, String(vars.year || new Date().getFullYear()));
    body = body.replace(/\[fullname\]/g, vars.owner || 'OWNER');
    return body;
  } catch {
    return `License: ${spdxId.toUpperCase()}\nCopyright (c) ${vars.year || new Date().getFullYear()} ${vars.owner || 'OWNER'}\n\nSee https://choosealicense.com/licenses/${spdxId}/ for full text.\n`;
  }
}

/**
 * Generate .gitattributes content.
 *
 * @param {string[]} stacks - Detected stacks.
 * @returns {string}
 */
export function generateGitattributes(stacks) {
  const lines = [
    '# Auto-detect text files and normalize line endings',
    '* text=auto',
    '',
    '# Source code',
    '*.c text',
    '*.h text',
    '*.md text',
    '*.json text',
    '*.yaml text',
    '*.yml text',
    '*.xml text',
    '*.toml text',
    '',
    '# Force LF for shell scripts and CI configs',
    '*.sh text eol=lf',
    '*.bash text eol=lf',
    '',
    '# Force CRLF for Windows-specific files',
    '*.bat text eol=crlf',
    '*.cmd text eol=crlf',
    '*.ps1 text eol=crlf',
    '*.sln text eol=crlf',
    '',
    '# Binary files',
    '*.png binary',
    '*.jpg binary',
    '*.jpeg binary',
    '*.gif binary',
    '*.ico binary',
    '*.webp binary',
    '*.svg text',
    '*.pdf binary',
    '*.zip binary',
    '*.tar.gz binary',
    '*.woff binary',
    '*.woff2 binary',
    '*.ttf binary',
    '*.eot binary',
    '',
    '# Linguist overrides',
    '*.min.js linguist-generated',
    '*.min.css linguist-generated',
  ];

  // Stack-specific linguist overrides
  if (stacks.includes('node')) {
    lines.push('pnpm-lock.yaml linguist-generated');
    lines.push('package-lock.json linguist-generated');
    lines.push('yarn.lock linguist-generated');
  }
  if (stacks.includes('go')) {
    lines.push('go.sum linguist-generated');
  }
  if (stacks.includes('rust')) {
    lines.push('Cargo.lock linguist-generated');
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Generate a README.md skeleton.
 *
 * @param {{ name: string, description?: string, stacks?: string[] }} opts
 * @returns {string}
 */
export function generateReadme(opts) {
  const name = opts.name || 'Project';
  const desc = opts.description || 'A brief description of the project.';
  const lines = [
    `# ${name}`,
    '',
    desc,
    '',
    '## Features',
    '',
    '- Feature 1',
    '- Feature 2',
    '',
    '## Getting Started',
    '',
    '### Prerequisites',
    '',
    '<!-- List prerequisites here -->',
    '',
    '### Installation',
    '',
    '```sh',
    '# Clone the repository',
    `git clone https://github.com/OWNER/${name.toLowerCase().replace(/\s+/g, '-')}.git`,
    `cd ${name.toLowerCase().replace(/\s+/g, '-')}`,
    '',
    '# Install dependencies',
  ];

  if (opts.stacks?.includes('node')) {
    lines.push('npm install');
  } else if (opts.stacks?.includes('python')) {
    lines.push('pip install -e .');
  } else if (opts.stacks?.includes('go')) {
    lines.push('go mod download');
  } else if (opts.stacks?.includes('rust')) {
    lines.push('cargo build');
  } else if (opts.stacks?.includes('dotnet')) {
    lines.push('dotnet restore');
  } else {
    lines.push('# TODO: add install command');
  }

  lines.push(
    '```',
    '',
    '### Usage',
    '',
    '```sh',
    '# TODO: add usage example',
    '```',
    '',
    '## Contributing',
    '',
    'See [CONTRIBUTING.md](CONTRIBUTING.md) for details.',
    '',
    '## License',
    '',
    `[LICENSE](LICENSE)`,
    '',
  );

  return lines.join('\n');
}

/**
 * Generate CONTRIBUTING.md tailored to the detected stack.
 *
 * @param {{ name: string, stacks: string[], pkgManager?: string }} opts
 * @returns {string}
 */
export function generateContributing(opts) {
  const name = opts.name || 'this project';
  let installCmd = '# Install dependencies';
  let testCmd = '# Run tests';

  if (opts.stacks.includes('node')) {
    const pm = opts.pkgManager || 'npm';
    installCmd = `${pm} install`;
    testCmd = `${pm} test`;
  } else if (opts.stacks.includes('python')) {
    installCmd = 'pip install -e ".[dev]"';
    testCmd = 'pytest';
  } else if (opts.stacks.includes('go')) {
    installCmd = 'go mod download';
    testCmd = 'go test ./...';
  } else if (opts.stacks.includes('rust')) {
    installCmd = 'cargo build';
    testCmd = 'cargo test';
  } else if (opts.stacks.includes('dotnet')) {
    installCmd = 'dotnet restore';
    testCmd = 'dotnet test';
  } else if (opts.stacks.includes('ruby')) {
    installCmd = 'bundle install';
    testCmd = 'bundle exec rake test';
  }

  return `# Contributing to ${name}

Thank you for your interest in contributing! Please read this guide before
submitting issues or pull requests.

## Code of Conduct

This project adheres to the [Contributor Covenant Code of Conduct](CODE_OF_CONDUCT.md).
By participating, you are expected to uphold this code.

## Getting Started

1. Fork the repository
2. Clone your fork:
   \`\`\`sh
   git clone https://github.com/YOUR-USERNAME/${name.toLowerCase().replace(/\s+/g, '-')}.git
   cd ${name.toLowerCase().replace(/\s+/g, '-')}
   \`\`\`
3. Create a branch:
   \`\`\`sh
   git checkout -b feat/my-feature
   \`\`\`
4. Install dependencies:
   \`\`\`sh
   ${installCmd}
   \`\`\`
5. Make your changes
6. Run tests:
   \`\`\`sh
   ${testCmd}
   \`\`\`

## Pull Request Process

1. Update documentation for any new features
2. Add or update tests for your changes
3. Ensure CI passes
4. Reference the related issue: \`Closes #123\`
5. Maintainers will review within a few business days

## Commit Convention

This project uses [Conventional Commits](https://www.conventionalcommits.org/):

- \`feat:\` new feature
- \`fix:\` bug fix
- \`docs:\` documentation only
- \`chore:\` maintenance, dependencies
- \`test:\` adding or updating tests
- \`refactor:\` code restructure without behavior change

## Reporting Bugs

Use the [bug report template](.github/ISSUE_TEMPLATE/bug_report.yml).
Include steps to reproduce, expected behavior, and your environment details.

## Requesting Features

Use the [feature request template](.github/ISSUE_TEMPLATE/feature_request.yml).
Describe the problem, your proposed solution, and any alternatives considered.
`;
}

/**
 * Generate CODE_OF_CONDUCT.md using Contributor Covenant v2.1.
 *
 * @param {{ contactEmail: string }} opts
 * @returns {string}
 */
export function generateCodeOfConduct(opts) {
  const contact = opts.contactEmail || '[INSERT CONTACT METHOD]';
  return `# Contributor Covenant Code of Conduct

## Our Pledge

We as members, contributors, and leaders pledge to make participation in our
community a harassment-free experience for everyone, regardless of age, body
size, visible or invisible disability, ethnicity, sex characteristics, gender
identity and expression, level of experience, education, socio-economic status,
nationality, personal appearance, race, caste, color, religion, or sexual
identity and orientation.

We pledge to act and interact in ways that contribute to an open, welcoming,
diverse, inclusive, and healthy community.

## Our Standards

Examples of behavior that contributes to a positive environment for our
community include:

* Demonstrating empathy and kindness toward other people
* Being respectful of differing opinions, viewpoints, and experiences
* Giving and gracefully accepting constructive feedback
* Accepting responsibility and apologizing to those affected by our mistakes,
  and learning from the experience
* Focusing on what is best not just for us as individuals, but for the overall
  community

Examples of unacceptable behavior include:

* The use of sexualized language or imagery, and sexual attention or advances of
  any kind
* Trolling, insulting or derogatory comments, and personal or political attacks
* Public or private harassment
* Publishing others' private information, such as a physical or email address,
  without their explicit permission
* Other conduct which could reasonably be considered inappropriate in a
  professional setting

## Enforcement Responsibilities

Community leaders are responsible for clarifying and enforcing our standards of
acceptable behavior and will take appropriate and fair corrective action in
response to any behavior that they deem inappropriate, threatening, offensive,
or harmful.

Community leaders have the right and responsibility to remove, edit, or reject
comments, commits, code, wiki edits, issues, and other contributions that are
not aligned to this Code of Conduct, and will communicate reasons for moderation
decisions when appropriate.

## Scope

This Code of Conduct applies within all community spaces, and also applies when
an individual is officially representing the community in public spaces.
Examples of representing our community include using an official email address,
posting via an official social media account, or acting as an appointed
representative at an online or offline event.

## Enforcement

Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported to the community leaders responsible for enforcement at
${contact}.

All complaints will be reviewed and investigated promptly and fairly.

All community leaders are obligated to respect the privacy and security of the
reporter of any incident.

## Enforcement Guidelines

Community leaders will follow these Community Impact Guidelines in determining
the consequences for any action they deem in violation of this Code of Conduct:

### 1. Correction

**Community Impact**: Use of inappropriate language or other behavior deemed
unprofessional or unwelcome in the community.

**Consequence**: A private, written warning from community leaders, providing
clarity around the nature of the violation and an explanation of why the
behavior was inappropriate. A public apology may be requested.

### 2. Warning

**Community Impact**: A violation through a single incident or series of
actions.

**Consequence**: A warning with consequences for continued behavior. No
interaction with the people involved, including unsolicited interaction with
those enforcing the Code of Conduct, for a specified period of time. This
includes avoiding interactions in community spaces as well as external channels
like social media. Violating these terms may lead to a temporary or permanent
ban.

### 3. Temporary Ban

**Community Impact**: A serious violation of community standards, including
sustained inappropriate behavior.

**Consequence**: A temporary ban from any sort of interaction or public
communication with the community for a specified period of time. No public or
private interaction with the people involved, including unsolicited interaction
with those enforcing the Code of Conduct, is allowed during this period.
Violating these terms may lead to a permanent ban.

### 4. Permanent Ban

**Community Impact**: Demonstrating a pattern of violation of community
standards, including sustained inappropriate behavior, harassment of an
individual, or aggression toward or disparagement of classes of individuals.

**Consequence**: A permanent ban from any sort of public interaction within the
community.

## Attribution

This Code of Conduct is adapted from the [Contributor Covenant][homepage],
version 2.1, available at
[https://www.contributor-covenant.org/version/2/1/code_of_conduct.html][v2.1].

Community Impact Guidelines were inspired by
[Mozilla's code of conduct enforcement ladder][Mozilla CoC].

For answers to common questions about this code of conduct, see the FAQ at
[https://www.contributor-covenant.org/faq][FAQ]. Translations are available at
[https://www.contributor-covenant.org/translations][translations].

[homepage]: https://www.contributor-covenant.org
[v2.1]: https://www.contributor-covenant.org/version/2/1/code_of_conduct.html
[Mozilla CoC]: https://github.com/mozilla/diversity
[FAQ]: https://www.contributor-covenant.org/faq
[translations]: https://www.contributor-covenant.org/translations
`;
}

/**
 * Generate SECURITY.md.
 *
 * @param {{ contactEmail: string, name?: string }} opts
 * @returns {string}
 */
export function generateSecurity(opts) {
  const contact = opts.contactEmail || 'security@example.com';
  const name = opts.name || 'this project';
  return `# Security Policy

## Reporting a Vulnerability

Please do **not** open a public GitHub issue for security vulnerabilities.

Instead, please report them to: **${contact}**

Include the following in your report:

- Description of the vulnerability
- Steps to reproduce
- Potential impact
- Suggested fix (if any)

You will receive a response within 48 hours acknowledging the report. We will
work with you to understand and address the issue before any public disclosure.

We will credit reporters in release notes unless you prefer to remain anonymous.

## Supported Versions

<!-- Update this table as versions are released -->

| Version | Supported |
| ------- | --------- |
| latest  | Yes       |

## Disclosure Policy

When a vulnerability is confirmed, we will:

1. Develop and test a fix
2. Release a patched version
3. Publish a security advisory on GitHub
4. Credit the reporter (with permission)
`;
}

/**
 * Generate .github/ISSUE_TEMPLATE/bug_report.yml (YAML form format).
 *
 * @returns {string}
 */
export function generateBugReportTemplate() {
  return `name: Bug Report
description: File a bug report to help us improve.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide relevant environment details.
      placeholder: |
        - OS: [e.g. Windows 11, macOS 15, Ubuntu 24.04]
        - Runtime: [e.g. Node.js 22, Python 3.12]
        - Version: [e.g. 1.2.3]
      render: markdown

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
`;
}

/**
 * Generate .github/ISSUE_TEMPLATE/feature_request.yml (YAML form format).
 *
 * @returns {string}
 */
export function generateFeatureRequestTemplate() {
  return `name: Feature Request
description: Suggest an idea for this project.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
`;
}

/**
 * Generate .github/ISSUE_TEMPLATE/config.yml.
 *
 * @param {{ blankIssues?: boolean, discussionsUrl?: string }} opts
 * @returns {string}
 */
export function generateIssueTemplateConfig(opts = {}) {
  const lines = [`blank_issues_enabled: ${opts.blankIssues !== false}`];

  if (opts.discussionsUrl) {
    lines.push(
      'contact_links:',
      '  - name: Questions and Discussions',
      `    url: ${opts.discussionsUrl}`,
      '    about: Please ask and answer questions here instead of opening issues.',
    );
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Generate .github/PULL_REQUEST_TEMPLATE.md.
 *
 * @returns {string}
 */
export function generatePRTemplate() {
  return `## Description

<!-- Describe your changes and the motivation behind them -->

## Related Issue(s)

Closes #<!-- issue number -->

## Type of Change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [ ] My code follows the project's coding style
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix or feature works
- [ ] New and existing tests pass locally
- [ ] I have updated the documentation as needed
- [ ] Any dependent changes have been merged and published
`;
}

/**
 * Generate .github/dependabot.yml.
 *
 * @param {string[]} ecosystems - Dependabot ecosystem identifiers.
 * @param {{ schedule?: string }} opts
 * @returns {string}
 */
export function generateDependabot(ecosystems, opts = {}) {
  const schedule = opts.schedule || 'weekly';
  const lines = [
    'version: 2',
    'updates:',
  ];

  for (const eco of ecosystems) {
    lines.push(
      `  - package-ecosystem: "${eco}"`,
      '    directory: "/"',
      '    schedule:',
      `      interval: "${schedule}"`,
      '    open-pull-requests-limit: 10',
      '',
    );
  }

  return lines.join('\n');
}

/**
 * Generate a basic CI workflow based on the primary detected stack.
 *
 * @param {string[]} stacks - Detected stacks.
 * @param {{ pkgManager?: string }} opts
 * @returns {string}
 */
export function generateCIWorkflow(stacks, opts = {}) {
  const primary = stacks[0];
  if (!primary) return null;

  const header = `name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

`;

  const templates = {
    node: () => {
      const pm = opts.pkgManager || 'npm';
      const install = pm === 'pnpm'
        ? `      - uses: pnpm/action-setup@v4\n      - run: pnpm install --frozen-lockfile`
        : pm === 'yarn'
          ? '      - run: yarn install --frozen-lockfile'
          : '      - run: npm ci';
      const test = pm === 'pnpm' ? 'pnpm test' : pm === 'yarn' ? 'yarn test' : 'npm test';
      return `${header}jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js \${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: \${{ matrix.node-version }}
${install}
      - run: ${pm} run build --if-present
      - run: ${test}
`;
    },

    python: () => `${header}jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python \${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: \${{ matrix.python-version }}
      - run: pip install -e ".[dev]"
      - run: pytest
`,

    go: () => `${header}jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go build -v ./...
      - run: go test -v ./...
`,

    rust: () => `${header}jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy -- -D warnings
`,

    dotnet: () => `${header}jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-build --verbosity normal
`,

    ruby: () => `${header}jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.2", "3.3"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: \${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rake test
`,

    java: () => `${header}jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build with Gradle
        run: ./gradlew build
`,
  };

  const gen = templates[primary];
  return gen ? gen() : null;
}

/**
 * Generate .github/CODEOWNERS.
 *
 * @param {Array<{ pattern: string, owners: string[] }>} entries
 * @returns {string}
 */
export function generateCodeowners(entries) {
  if (!entries || entries.length === 0) {
    return '# CODEOWNERS\n# Add path patterns and owner GitHub usernames/teams.\n# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners\n\n* @OWNER\n';
  }

  const lines = [
    '# CODEOWNERS',
    '# Automatically request reviews from these owners when files change.',
    '# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners',
    '',
  ];
  for (const e of entries) {
    lines.push(`${e.pattern}  ${e.owners.join(' ')}`);
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * Generate .github/FUNDING.yml.
 *
 * @param {object} platforms - Platform-to-username mapping.
 * @returns {string}
 */
export function generateFunding(platforms) {
  const lines = ['# Funding platforms'];
  for (const [platform, value] of Object.entries(platforms)) {
    if (Array.isArray(value)) {
      lines.push(`${platform}: [${value.map(v => `"${v}"`).join(', ')}]`);
    } else {
      lines.push(`${platform}: ${value}`);
    }
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * Generate .editorconfig.
 *
 * @param {string[]} stacks - Detected stacks.
 * @returns {string}
 */
export function generateEditorconfig(stacks) {
  const lines = [
    '# EditorConfig: https://editorconfig.org',
    'root = true',
    '',
    '[*]',
    'charset = utf-8',
    'end_of_line = lf',
    'insert_final_newline = true',
    'trim_trailing_whitespace = true',
    'indent_style = space',
    'indent_size = 2',
    '',
  ];

  if (stacks.includes('python')) {
    lines.push('[*.{py,pyi}]', 'indent_size = 4', '');
  }
  if (stacks.includes('go')) {
    lines.push('[*.go]', 'indent_style = tab', 'indent_size = 4', '');
  }
  if (stacks.includes('rust')) {
    lines.push('[*.rs]', 'indent_size = 4', '');
  }
  if (stacks.includes('java')) {
    lines.push('[*.java]', 'indent_size = 4', '');
  }
  if (stacks.includes('dotnet')) {
    lines.push('[*.{cs,fs,vb}]', 'indent_size = 4', '');
    lines.push('[*.sln]', 'end_of_line = crlf', '');
  }

  lines.push(
    '[Makefile]',
    'indent_style = tab',
    '',
    '[*.md]',
    'trim_trailing_whitespace = false',
    '',
    '[*.{yml,yaml}]',
    'indent_size = 2',
    '',
    '[*.{bat,cmd}]',
    'end_of_line = crlf',
    '',
  );

  return lines.join('\n');
}

/**
 * Generate CHANGELOG.md skeleton.
 *
 * @param {{ name?: string }} opts
 * @returns {string}
 */
export function generateChangelog(opts = {}) {
  const today = new Date().toISOString().slice(0, 10);
  return `# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

### Added

- Initial project setup
`;
}

/**
 * Write a file, creating parent directories as needed.
 * Returns true if the file was created, false if it already existed.
 *
 * @param {string} filePath - Absolute path.
 * @param {string} content - File content.
 * @param {{ force?: boolean }} opts
 * @returns {boolean}
 */
export function safeWrite(filePath, content, opts = {}) {
  if (existsSync(filePath) && !opts.force) {
    return false;
  }
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, content, 'utf-8');
  return true;
}

/**
 * Generate all files based on configuration.
 *
 * @param {string} dir - Target directory.
 * @param {object} config - Generation configuration.
 * @returns {Promise<Array<{ path: string, created: boolean, skipped: string|null }>>}
 */
export async function generateAll(dir, config) {
  const results = [];
  const write = (relPath, content) => {
    const abs = join(dir, relPath);
    const created = safeWrite(abs, content, { force: config.force });
    results.push({
      path: relPath,
      created,
      skipped: created ? null : 'already exists',
    });
  };

  const skip = config.skip || new Set();
  const stacks = config.stacks || [];

  // .gitignore
  if (!skip.has('gitignore')) {
    const templates = gitignoreTemplates(stacks);
    const content = await fetchGitignore(templates);
    write('.gitignore', content);
  }

  // .gitattributes
  if (!skip.has('gitattributes')) {
    write('.gitattributes', generateGitattributes(stacks));
  }

  // LICENSE
  if (!skip.has('license') && config.license) {
    const content = await fetchLicense(config.license, {
      owner: config.owner,
      year: config.year,
    });
    write('LICENSE', content);
  }

  // README.md
  if (!skip.has('readme')) {
    write('README.md', generateReadme({
      name: config.name,
      description: config.description,
      stacks,
    }));
  }

  // CONTRIBUTING.md
  if (!skip.has('contributing')) {
    write('CONTRIBUTING.md', generateContributing({
      name: config.name,
      stacks,
      pkgManager: config.pkgManager,
    }));
  }

  // CODE_OF_CONDUCT.md
  if (!skip.has('code-of-conduct')) {
    write('CODE_OF_CONDUCT.md', generateCodeOfConduct({
      contactEmail: config.cocContact,
    }));
  }

  // SECURITY.md
  if (!skip.has('security')) {
    write('SECURITY.md', generateSecurity({
      contactEmail: config.securityContact,
      name: config.name,
    }));
  }

  // Issue templates
  if (!skip.has('bug-report-template')) {
    write('.github/ISSUE_TEMPLATE/bug_report.yml', generateBugReportTemplate());
  }
  if (!skip.has('feature-request-template')) {
    write('.github/ISSUE_TEMPLATE/feature_request.yml', generateFeatureRequestTemplate());
  }
  if (!skip.has('issue-template-config')) {
    write('.github/ISSUE_TEMPLATE/config.yml', generateIssueTemplateConfig({
      blankIssues: config.blankIssues,
      discussionsUrl: config.discussionsUrl,
    }));
  }

  // PR template
  if (!skip.has('pr-template')) {
    write('.github/PULL_REQUEST_TEMPLATE.md', generatePRTemplate());
  }

  // dependabot.yml
  if (!skip.has('dependabot')) {
    const ecosystems = dependabotEcosystems(stacks);
    write('.github/dependabot.yml', generateDependabot(ecosystems, {
      schedule: config.dependabotSchedule,
    }));
  }

  // CI workflow
  if (!skip.has('ci-workflow')) {
    const workflow = generateCIWorkflow(stacks, {
      pkgManager: config.pkgManager,
    });
    if (workflow) {
      write('.github/workflows/ci.yml', workflow);
    }
  }

  // CODEOWNERS
  if (!skip.has('codeowners')) {
    write('.github/CODEOWNERS', generateCodeowners(config.codeowners));
  }

  // FUNDING.yml
  if (!skip.has('funding') && config.funding) {
    write('.github/FUNDING.yml', generateFunding(config.funding));
  }

  // CHANGELOG.md
  if (!skip.has('changelog')) {
    write('CHANGELOG.md', generateChangelog({ name: config.name }));
  }

  // .editorconfig
  if (!skip.has('editorconfig')) {
    write('.editorconfig', generateEditorconfig(stacks));
  }

  return results;
}

// CLI entry point
if (process.argv[1] && process.argv[1].endsWith('generate.mjs')) {
  const args = process.argv.slice(2);
  const dir = args.find(a => !a.startsWith('-')) || process.cwd();
  console.log('Usage: import { generateAll } from "./generate.mjs" and call programmatically.');
  console.log('Or use SKILL.md instructions to invoke via Copilot agent.');
}
