// test/smoke.test.mjs — boots this canvas's runtime over HTTP and exercises
// its actions. Generated by create-canvas-app. Run:  node test/smoke.test.mjs
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const home = await mkdtemp(join(tmpdir(), "canvas-app-smoke-"));
process.env.COPILOT_HOME = home;

const { canvasConfig } = await import("../canvas.mjs");
const { createCanvasRuntime } = await import("../canvas-kit/server.mjs");
const runtime = createCanvasRuntime(canvasConfig);

let passed = 0;
async function test(label, fn) {
  try {
    await fn();
    passed++;
    console.log(`  ok  ${label}`);
  } catch (e) {
    console.error(`FAIL  ${label}\n      ${e.message}`);
    process.exitCode = 1;
    throw e;
  }
}
const post = (url, actionName, input) =>
  fetch(new URL("/action", url), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ actionName, input }),
  }).then(async (r) => ({ status: r.status, body: await r.json() }));
const getState = (url) => fetch(new URL("/state", url)).then((r) => r.json());

try {
  const open = await runtime.openInstance({
    instanceId: "smoke",
    input: {},
    ctx: { instanceId: "smoke", input: {} },
  });
  await test("opens on a loopback url", () =>
    assert.match(open.url, /^http:\/\/127\.0\.0\.1:\d+\/$/));
  await test("GET /state starts empty", async () => {
    const s = await getState(open.url);
    assert.deepEqual(s.items, []);
  });

  let id;
  await test("add_item adds an item", async () => {
    const { body } = await post(open.url, "add_item", { text: "first" });
    assert.equal(body.ok, true);
    id = body.result.id;
    assert.ok(id);
    const s = await getState(open.url);
    assert.equal(s.items.length, 1);
    assert.equal(s.items[0].text, "first");
  });

  await test("toggle_item flips done", async () => {
    await post(open.url, "toggle_item", { id });
    const s = await getState(open.url);
    assert.equal(s.items[0].done, true);
  });

  await test("list_items summarizes for the agent", async () => {
    const { body } = await post(open.url, "list_items", {});
    assert.equal(body.result.count, 1);
  });

  await test("remove_item removes it", async () => {
    const { body } = await post(open.url, "remove_item", { id });
    assert.equal(body.result.removed, 1);
    const s = await getState(open.url);
    assert.deepEqual(s.items, []);
  });
} finally {
  await runtime.shutdown();
  await rm(home, { recursive: true, force: true });
}

console.log(`\n${passed} checks passed`);
