#!/usr/bin/env node
/**
 * generate-report.mjs
 *
 * Produces the full Model Intel report as a Markdown file.
 * Usage: node scripts/generate-report.mjs [--output path] [--quick]
 *
 * --quick: Skip web research, use built-in registry only.
 * --output: Custom output path (default: ./model-intel-report.md)
 */

import { MODEL_REGISTRY, PROVIDERS, groupByProvider, rankBy, recommendFor, TASK_PROFILES } from './registry.mjs';
import { barChart, table, radarChart, scatterPlot, timeline, headToHead, decisionTree } from './charts.mjs';

const args = process.argv.slice(2);
const quick = args.includes('--quick');
const outputIdx = args.indexOf('--output');
const outputPath = outputIdx >= 0 && args[outputIdx + 1] ? args[outputIdx + 1] : null;

/**
 * Generate the complete report content.
 */
function generateReport() {
  const now = new Date().toISOString().slice(0, 19).replace('T', ' ');
  const sections = [];

  // ─── Header ─────────────────────────────────────────────────────────────────
  sections.push(`# 🧠 Model Intelligence Report

> Generated: ${now}
> Models discovered: ${MODEL_REGISTRY.length}
> Providers: ${Object.keys(PROVIDERS).map(k => PROVIDERS[k].emoji + ' ' + PROVIDERS[k].name).join(', ')}
> Mode: ${quick ? 'Quick (registry only)' : 'Full (with research)'}

---
`);

  // ─── Section 1: Model Census ────────────────────────────────────────────────
  sections.push(generateCensus());

  // ─── Section 2: Architecture Cards ──────────────────────────────────────────
  sections.push(generateArchitectureCards());

  // ─── Section 3: Benchmark Dashboard ─────────────────────────────────────────
  sections.push(generateBenchmarkDashboard());

  // ─── Section 4: Capability Radar ────────────────────────────────────────────
  sections.push(generateCapabilityRadar());

  // ─── Section 5: Strengths & Weaknesses ──────────────────────────────────────
  sections.push(generateStrengthsWeaknesses());

  // ─── Section 6: Decision Tree ───────────────────────────────────────────────
  sections.push(generateDecisionTree());

  // ─── Section 7: Head-to-Head ────────────────────────────────────────────────
  sections.push(generateHeadToHead());

  // ─── Section 8: Cost/Performance Frontier ───────────────────────────────────
  sections.push(generateCostPerformance());

  // ─── Section 9: Context Window Guide ────────────────────────────────────────
  sections.push(generateContextGuide());

  // ─── Section 10: Release Timeline ───────────────────────────────────────────
  sections.push(generateTimeline());

  // ─── Section 11: Model Pairing Strategies ───────────────────────────────────
  sections.push(generatePairingStrategies());

  // ─── Section 12: Emerging Patterns ──────────────────────────────────────────
  sections.push(generateEmergingPatterns());

  // ─── Footer ─────────────────────────────────────────────────────────────────
  sections.push(`---

## Methodology

Scores are normalized 0-100 composites derived from:
- Official provider benchmarks (SWE-bench, HumanEval, MATH, MMLU)
- Independent evaluations (Aider polyglot, LiveCodeBench, LMSYS Arena)
- Community consensus from practical usage reports
- Copilot-specific performance observations (tool use, multi-file edits)

**Disclaimer**: Model capabilities evolve rapidly. This report reflects data available
at generation time. Re-run \`model-intel\` for an updated assessment.

---
*Generated by model-intel skill v1.0.0*
`);

  return sections.join('\n');
}

// ─── Section Generators ───────────────────────────────────────────────────────

function generateCensus() {
  const groups = groupByProvider();
  const rows = [];

  for (const [provKey, models] of groups) {
    for (const m of models) {
      rows.push([
        PROVIDERS[provKey].emoji,
        m.name,
        m.id,
        m.contextTiers.join(', '),
        m.effortLevels.join(', ') || 'n/a',
        `${m.contextWindow}K`,
        m.tier,
        m.releaseDate,
      ]);
    }
  }

  const t = table({
    title: '1. Model Census',
    headers: ['', 'Model', 'ID', 'Context Tiers', 'Effort Levels', 'Window', 'Tier', 'Released'],
    rows,
  });

  const summary = `
**Summary by provider:**
${[...groups.entries()].map(([k, v]) => `- ${PROVIDERS[k].emoji} ${PROVIDERS[k].name}: ${v.length} models`).join('\n')}

**By tier:**
- Standard (included): ${MODEL_REGISTRY.filter(m => m.tier === 'standard').length} models
- Premium (costs extra): ${MODEL_REGISTRY.filter(m => m.tier === 'premium').length} models
`;

  return `## 📋 Model Census\n${t}\n${summary}`;
}

function generateArchitectureCards() {
  const families = new Map();
  for (const m of MODEL_REGISTRY) {
    const key = `${m.provider}/${m.family}`;
    if (!families.has(key)) families.set(key, []);
    families.get(key).push(m);
  }

  const cards = [];
  for (const [key, models] of families) {
    const rep = models[0];
    const versions = models.map(m => m.name).join(', ');
    cards.push(`
### ${PROVIDERS[rep.provider].emoji} ${key.split('/')[1].toUpperCase()} Family

| Property | Value |
|----------|-------|
| Provider | ${PROVIDERS[rep.provider].name} |
| Models | ${versions} |
| Architecture | ${rep.architecture} |
| Context Window | ${rep.contextWindow}K tokens |
| Tier | ${rep.tier} |
`);
  }

  return `## 🏗️ Architecture Cards\n${cards.join('\n')}`;
}

function generateBenchmarkDashboard() {
  const dimensions = [
    { key: 'codeGeneration', label: 'Code Generation (SWE-bench, HumanEval proxy)' },
    { key: 'reasoning', label: 'Reasoning (MATH, ARC, BBH proxy)' },
    { key: 'codeReview', label: 'Code Review (precision/recall proxy)' },
    { key: 'multiFile', label: 'Multi-file Understanding' },
    { key: 'toolUse', label: 'Tool Use / Agentic Performance' },
  ];

  const charts = [];
  for (const dim of dimensions) {
    const ranked = rankBy(dim.key).slice(0, 10);
    const data = ranked.map(m => ({ name: m.name, value: m.scores[dim.key] }));
    charts.push(`\n#### ${dim.label}\n\n\`\`\`\n${barChart(data)}\n\`\`\``);
  }

  return `## 📊 Benchmark Dashboard\n\nNormalized scores (0-100) across key capability areas:\n${charts.join('\n')}`;
}

function generateCapabilityRadar() {
  // Show radar for top models from each provider
  const highlights = [
    MODEL_REGISTRY.find(m => m.id === 'claude-sonnet-5'),
    MODEL_REGISTRY.find(m => m.id === 'claude-opus-4.8'),
    MODEL_REGISTRY.find(m => m.id === 'gpt-5.6-sol'),
    MODEL_REGISTRY.find(m => m.id === 'gpt-5.5'),
    MODEL_REGISTRY.find(m => m.id === 'gemini-3.1-pro-preview'),
    MODEL_REGISTRY.find(m => m.id === 'gemini-3.5-flash'),
  ].filter(Boolean);

  const radars = highlights.map(m => `\n\`\`\`\n${radarChart({ modelName: m.name, scores: m.scores })}\n\`\`\``);

  return `## 🎯 Capability Radar\n\nMulti-dimensional profiles for flagship models:\n${radars.join('\n')}`;
}

function generateStrengthsWeaknesses() {
  const entries = MODEL_REGISTRY.map(m => {
    const scores = Object.entries(m.scores);
    const sorted = scores.sort((a, b) => b[1] - a[1]);
    const strengths = sorted.slice(0, 3).map(([k, v]) => `${formatDimLabel(k)} (${v})`);
    const weaknesses = sorted.slice(-3).reverse().map(([k, v]) => `${formatDimLabel(k)} (${v})`);

    return `
### ${PROVIDERS[m.provider].emoji} ${m.name}

| Strengths 💪 | Weaknesses 📉 |
|-------------|--------------|
| ${strengths[0]} | ${weaknesses[0]} |
| ${strengths[1]} | ${weaknesses[1]} |
| ${strengths[2]} | ${weaknesses[2]} |

> *${m.architecture}*
`;
  });

  return `## 💪📉 Strengths & Weaknesses Matrix\n${entries.join('')}`;
}

function generateDecisionTree() {
  const decisions = [];

  for (const [, profile] of Object.entries(TASK_PROFILES)) {
    const ranked = recommendFor(profile.weights);
    const best = ranked[0];
    const alt = ranked[1];
    decisions.push({
      task: profile.label,
      recommended: `${best.name} (${best.tier})`,
      fallback: `${alt.name} (${alt.tier})`,
      reason: explainChoice(best, profile.weights),
    });
  }

  const tree = decisionTree(decisions);

  return `## 🌳 Decision Tree: Which Model for What?\n\n\`\`\`\n${tree}\n\`\`\``;
}

function generateHeadToHead() {
  const matchups = [
    ['claude-sonnet-4.6', 'claude-sonnet-5'],
    ['gpt-5.5', 'claude-opus-4.6'],
    ['gemini-3.5-flash', 'claude-haiku-4.5'],
    ['gpt-5.6-sol', 'claude-opus-4.8'],
    ['gpt-5.4-mini', 'gpt-5-mini'],
    ['claude-sonnet-5', 'gpt-5.6-terra'],
  ];

  const comparisons = matchups.map(([idA, idB]) => {
    const a = MODEL_REGISTRY.find(m => m.id === idA);
    const b = MODEL_REGISTRY.find(m => m.id === idB);
    if (!a || !b) return '';
    return `\n\`\`\`\n${headToHead(a, b)}\n\`\`\``;
  }).filter(Boolean);

  return `## ⚔️ Head-to-Head Comparisons\n\nCommon model matchups for frequently asked "which one?" questions:\n${comparisons.join('\n')}`;
}

function generateCostPerformance() {
  const points = MODEL_REGISTRY.map(m => {
    const avgQuality = Object.values(m.scores).reduce((s, v) => s + v, 0) / Object.values(m.scores).length;
    return { name: m.name, x: m.scores.costEfficiency, y: Math.round(avgQuality) };
  });

  const chart = scatterPlot(points, {
    xLabel: 'Cost Efficiency →',
    yLabel: '↑ Average Quality',
  });

  // Frontier analysis
  const frontier = [...points].sort((a, b) => {
    const scoreA = a.x * 0.4 + a.y * 0.6;
    const scoreB = b.x * 0.4 + b.y * 0.6;
    return scoreB - scoreA;
  });

  const analysis = `
**Pareto frontier (best quality per cost):**
${frontier.slice(0, 5).map((p, i) => `${i + 1}. ${p.name} (quality: ${p.y}, efficiency: ${p.x})`).join('\n')}

**Best value picks:**
- 🏆 Best overall value: ${frontier[0].name}
- ⚡ Best for budget-conscious: ${points.sort((a, b) => b.x - a.x)[0].name}
- 🎯 Best quality regardless of cost: ${points.sort((a, b) => b.y - a.y)[0].name}
`;

  return `## 💰 Cost/Performance Frontier\n\n\`\`\`\n${chart}\n\`\`\`\n${analysis}`;
}

function generateContextGuide() {
  const rows = MODEL_REGISTRY
    .sort((a, b) => b.contextWindow - a.contextWindow)
    .map(m => [
      m.name,
      `${m.contextWindow}K`,
      m.contextTiers.includes('long_context') ? '✅' : '❌',
      contextGuidance(m),
    ]);

  const t = table({
    headers: ['Model', 'Window', 'Long Context', 'Practical Guidance'],
    rows,
  });

  return `## 📏 Context Window Guide

${t}

### Effective context utilization tips:

- **1M token models** (Gemini): Excellent for whole-repo analysis, but quality
  can degrade in the "lost middle" zone (tokens 200K-800K). Front-load important
  context.
- **256K models** (GPT-5.4/5.5/5.6): Sweet spot for large PRs and multi-file
  refactors. Needle-in-haystack performance is strong throughout.
- **200K models** (Claude family): Consistent quality across the full window.
  Best attention distribution of any provider at their context size.
- **128K models** (GPT-5 mini, MAI-Code): Sufficient for most single-file and
  small multi-file tasks. Context quality is high but capacity limits
  whole-repo analysis.

### When to use long_context tier:

Use \`context_tier: "long_context"\` when:
- Analyzing more than 50 files simultaneously
- PR diffs exceed 5000 lines
- The task requires understanding relationships across distant modules
- You're doing whole-codebase searches or architectural analysis
`;
}

function generateTimeline() {
  const events = MODEL_REGISTRY.map(m => ({
    date: m.releaseDate,
    label: m.name,
    provider: m.provider,
  }));

  const tl = timeline(events);

  return `## 📅 Release Timeline

\`\`\`
${tl}
\`\`\`

### Evolution patterns:
- **Anthropic**: Rapid iteration on Sonnet (4.5 → 4.6 → 5 in ~4 months); Opus
  releases track ~1 month behind each Sonnet.
- **OpenAI**: GPT-5 family expanding through specialization (mini, Codex) and
  frontier variants (Sol/Terra/Luna differentiation).
- **Google**: Focus on context length leadership (1M tokens) with Flash models
  competing on cost/speed.
- **Microsoft**: Entering with code-specialized models (MAI-Code) optimized
  for the Copilot ecosystem.
`;
}

function generatePairingStrategies() {
  return `## 🤝 Model Pairing Strategies

Multi-model workflows maximize quality while controlling cost. Use faster/cheaper
models for exploration and stronger models for final output.

### Recommended pairings:

| Workflow | Fast/Cheap Model | Strong/Deep Model | Why |
|----------|-----------------|-------------------|-----|
| Code Review | Haiku 4.5 (triage) | Opus 4.8 (deep analysis) | Haiku flags areas of concern; Opus dives deep on flagged sections |
| Refactoring | Sonnet 4.6 (plan) | Sonnet 5 (execute) | 4.6 explores approaches cheaply; 5 implements the chosen path |
| Architecture | GPT-5.5 (research) | Opus 4.7 (design) | GPT-5.5's large context digests the codebase; Opus designs the solution |
| Test Generation | GPT-5.4 mini (bulk) | Sonnet 5 (edge cases) | Mini generates the obvious tests fast; Sonnet 5 handles tricky scenarios |
| Security Audit | Gemini 3.5 Flash (scan) | GPT-5.6 Sol (analyze) | Flash's 1M context scans everything; Sol reasons about exploit chains |
| Documentation | Haiku 4.5 (draft) | Luna (polish) | Haiku generates structure quickly; Luna refines the prose |
| Debugging | Sonnet 4.6 (reproduce) | Opus 4.8 (root cause) | Sonnet traces the bug; Opus finds the architectural fix |

### Cost optimization pattern:

\`\`\`
┌─────────────────────────────────────────────────────────────┐
│  Standard tier (included)  →  Premium tier (when needed)    │
│                                                             │
│  Haiku 4.5 ──┐                                             │
│  GPT-5 mini ─┤── Exploration ──→ Sonnet 5 ──┐              │
│  Flash 3.5 ──┘    & triage       GPT-5.6 Sol ├─ Final pass │
│                                  Opus 4.8 ───┘              │
└─────────────────────────────────────────────────────────────┘
\`\`\`

### When to skip pairing (use one model):

- Simple, well-scoped tasks (< 100 lines changed): use Sonnet 4.6 alone
- Pure speed tasks (formatting, renaming): use Haiku 4.5 alone
- Maximum quality, no budget concern: use Opus 4.8 alone with max effort
`;
}

function generateEmergingPatterns() {
  return `## 🔮 Emerging Patterns & Trends

### What's changing fast:

1. **Effort/reasoning levels are the new frontier**: Models with \`xhigh\` and
   \`max\` effort produce dramatically better results on complex tasks. The gap
   between \`low\` and \`max\` effort on the same model can exceed the gap between
   different model families.

2. **Specialization over generalization**: GPT-5.6's Sol/Terra/Luna split shows
   providers moving toward task-optimized variants rather than one-size-fits-all.
   Expect more of this.

3. **Context windows are commoditizing**: 200K+ is now baseline. The differentiator
   is quality of attention within the window, not raw size.

4. **Tool use is a first-class capability**: Models explicitly trained for agentic
   workflows (Sonnet 5, GPT-5.6 Sol) consistently outperform others in multi-step
   tasks even when their raw reasoning scores are similar.

5. **Flash/mini models closing the gap**: Haiku 4.5 and GPT-5.4 mini deliver 80%+
   of flagship quality at 5-10x the speed. For many tasks, they're the right choice.

6. **Multi-model is becoming standard**: The best results come from composing
   models rather than picking one. Fast models for exploration, strong models for
   final output.

### Predictions for next quarter:

- Expect Claude Sonnet 5.x with improved speed (distilled from Opus)
- GPT-5.7 likely to unify Sol/Terra/Luna into a single model with mode switches
- Gemini Pro 3.5 with improved code benchmarks to challenge Claude on coding
- More Microsoft-trained models entering the Copilot ecosystem
- Effort level \`ultra\` (beyond max) for frontier reasoning tasks

### Model deprecation watch:

| Model | Status | Recommended Migration |
|-------|--------|----------------------|
| Claude Sonnet 4.5 | Stable, but superseded | Upgrade to Sonnet 4.6 (free) or 5 (premium) |
| GPT-5 mini | Stable | Consider GPT-5.4 mini for better quality at similar speed |
| Claude Opus 4.6 | Stable, superseded | Upgrade to Opus 4.7 or 4.8 |
`;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function formatDimLabel(dim) {
  return dim.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase()).trim();
}

function explainChoice(model, weights) {
  const topWeight = Object.entries(weights).sort((a, b) => b[1] - a[1])[0];
  return `Tops in ${formatDimLabel(topWeight[0]).toLowerCase()} (score: ${model.scores[topWeight[0]]})`;
}

function contextGuidance(model) {
  if (model.contextWindow >= 1000) return 'Whole-repo analysis, massive PRs';
  if (model.contextWindow >= 256) return 'Large multi-file tasks, big PRs';
  if (model.contextWindow >= 200) return 'Standard multi-file, most tasks';
  return 'Single-file focus, small tasks';
}

// ─── Main ─────────────────────────────────────────────────────────────────────

const report = generateReport();

if (outputPath) {
  const { writeFileSync } = await import('node:fs');
  writeFileSync(outputPath, report, 'utf8');
  console.log(`Report written to: ${outputPath}`);
} else {
  // Print to stdout for piping or direct consumption
  console.log(report);
}
